### ISSUE TITLE
Node.js engine in incidents requirements is not LTS - update?

### ISSUE THREAD

**Issue by qmacro** [SAP-samples/teched2022-AD265#7]
When running `npm install` in the `incidents/` directory, the following warning appears for me:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@acme/incidents-mgmt@1.0.0',
npm WARN EBADENGINE   required: { node: '^16.15' },
npm WARN EBADENGINE   current: { node: 'v18.13.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```

This relates to [the required Node.js engine version specified in the package.json](https://github.com/SAP-samples/teched2022-AD265/blob/main/incidents/package.json#L19) 

```
  "engines": {
    "node": "^16.15"
  }
```

which restricts the major version of Node.js to 16. I'm running 18.13.

Would it be worth considering this (which would cause that warning to not appear):

```
  "engines": {
    "node": ">=16.15"
  }
```

or is that too open?

**Comment by chgeo** [comment]
Thanks for bringing this up.
Yes, the app should definitely run w/ latest LTS (18 atm).

We also prefer the open `>=` approach, although there's people who prefer the closed option of 'locking' the version.
